apiVersion: v2
name: birb-nest
description: A Helm chart for Birb-Nest persistent cache service with instance isolation
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - cache
  - redis
  - postgresql
  - birb-nest
  - instance-isolation

maintainers:
  - name: BirdParty
    email: admin@birb.party

dependencies:
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
