{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "birb-nest.fullname" . }}
  labels:
    {{- include "birb-nest.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "birb-nest.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    # Allow from pods with specific labels
    - podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicy.clientLabels | nindent 10 }}
    # Allow from specific namespaces
    {{- range .Values.networkPolicy.allowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          name: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
  egress:
  # Allow DNS
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  # Allow to primary (for replicas)
  {{- if ne .Values.mode "primary" }}
  - to:
    - podSelector:
        matchLabels:
          app: birb-nest
          instance: primary
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  {{- end }}
  # Allow to Redis
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 6379
  # Allow to PostgreSQL (primary only)
  {{- if and (eq .Values.mode "primary") .Values.postgresql.enabled }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 5432
  {{- end }}
{{- end }}
