apiVersion: v1
kind: Service
metadata:
  name: {{ include "birb-nest.fullname" . }}
  labels:
    {{- include "birb-nest.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    # Explicitly disable load balancer
    service.beta.kubernetes.io/do-loadbalancer-enabled: "false"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "birb-nest.selectorLabels" . | nindent 4 }}
